### ISSUE TITLE
Support for IAP

### ISSUE THREAD

**Issue by yassine-labidi** [spotify/terraform-gke-kubeflow-cluster#8]
Hi Matt,
This unrelated, to the scope of this project, but I'm curious to know which manifest are you using to install kubeflow and how are you managing to setup IAP, if that's a feature you're providing with the kubeflow installation ?

**Comment by daikeshi** [comment]
hey @yassine-labidi, we are currently on kubeflow/manifests v0.7. For IAP setup we pretty much used the out-of-box deployment manifests except we are managing our own SSL certificate and hostname.
